// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ferovi.Models.EF;

[Table("MenusPrincipales", Schema = "Plat")]
public partial class MenusPrincipales
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Enlace { get; set; }

    public int Nivel { get; set; }

    public int? IdMenuPadre { get; set; }

    public int? IdIcono { get; set; }

    [ForeignKey("IdIcono")]
    [InverseProperty("MenusPrincipales")]
    public virtual Iconos IdIconoNavigation { get; set; }
}