// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ferovi.Models.EF;

[Table("Roles", Schema = "Plat")]
public partial class Roles
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Codigo { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [InverseProperty("IdRolNavigation")]
    public virtual ICollection<Usuarios_Roles> Usuarios_Roles { get; set; } = new List<Usuarios_Roles>();
}