// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ferovi.Models.EF;

[Table("Usuarios", Schema = "Plat")]
public partial class Usuarios
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PrimerApellido { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SegundoApellido { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Alias { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaCreacion { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<UsuariosHistorialesAccesos> UsuariosHistorialesAccesos { get; set; } = new List<UsuariosHistorialesAccesos>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Usuarios_Roles> Usuarios_Roles { get; set; } = new List<Usuarios_Roles>();
}