// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ferovi.Models.EF;

[Table("UsuariosHistorialAccesos", Schema = "Plat")]
public partial class UsuariosHistorialAccesos
{
    [Key]
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaUltimoAcceso { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("UsuariosHistorialAccesos")]
    public virtual Usuarios IdUsuarioNavigation { get; set; }
}